# -*- coding: utf-8 -*-
"""ML_LAB_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KO9gQuX7AISIaVnxqKKRGRbp0Mup6U5T
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("Lab 3 Session Data.xlsx",sheet_name ="marketing_campaign")

print(df.columns)

df.info()

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#A2
def label_encoding(data, columns):
    data = data.copy()

    encoder = LabelEncoder()

    for col in columns:
        data[col] = encoder.fit_transform(data[col].astype(str))

    return data

def one_hot_encoding(data, columns):
    data = data.copy()

    data = pd.get_dummies(data,
                          columns=columns,
                          drop_first=False)

    return data

#A3
print(df["Education"].unique())
print(df["Marital_Status"].unique())

categorical_cols = ["Education", "Marital_Status"]

# Label Encoding
label_df = label_encoding(df, categorical_cols)

# One Hot Encoding
onehot_df = one_hot_encoding(df, categorical_cols)

print("Original Shape :", df.shape)
print("Label Encoded Shape :", label_df.shape)
print("One Hot Shape :", onehot_df.shape)

print(label_df[["Education", "Marital_Status"]].head())

print(onehot_df.filter(regex="Education|Marital_Status").head())

#A4
def minkowski_distance(x, y, p):
    total = 0
    for i in range(len(x)):
        total += abs(x[i] - y[i]) ** p
    return total ** (1 / p)

A = [2, 3]
B = [5, 7]

print(minkowski_distance(A, B, 3))

#A5

import matplotlib.pyplot as plt

def minkowski_distance(x, y, p):
    total = 0
    for i in range(len(x)):
        total += abs(x[i] - y[i]) ** p
    return total ** (1 / p)

# Use the label encoded dataset (numeric values)
numeric_df = label_df.select_dtypes(include=['number'])

# Take any two feature vectors
A = numeric_df.iloc[0].values
B = numeric_df.iloc[1].values

p_values = []
distances = []

for p in range(1, 11):
    p_values.append(p)
    distances.append(minkowski_distance(A, B, p))

print("p\tDistance")
for p, d in zip(p_values, distances):
    print(f"{p}\t{d:.4f}")

plt.figure(figsize=(8,5))
plt.plot(p_values, distances, marker='o')
plt.title("Minkowski Distance (p = 1 to 10)")
plt.xlabel("p")
plt.ylabel("Distance")
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

#A6
from scipy.spatial.distance import minkowski
package_distance = minkowski(A,B,2)
print(package_distance)
my_distance = minkowski_distance(A,B,2)
print(my_distance)
difference = abs(package_distance - my_distance)
print(difference)

#A7
def dot_product(A,B):
  result = 0
  for i in range(len(A)):
    result += A[i]*B[i]
  return result

def euclidean_norm(A):
  total = 0
  for i in range(len(A)):
    total += A[i]**2
  return total**0.5

my_dot = dot_product(A, B)
my_norm_A = euclidean_norm(A)
my_norm_B = euclidean_norm(B)


numpy_dot = np.dot(A,B)
numpy_norm_A = np.linalg.norm(A)
numpy_norm_B = np.linalg.norm(B)

print("Dot Product")
print("My Function :", my_dot)
print("NumPy       :", numpy_dot)

print("\nEuclidean Norm of A")
print("My Function :", my_norm_A)
print("NumPy       :", numpy_norm_A)

print("\nEuclidean Norm of B")
print("My Function :", my_norm_B)
print("NumPy       :", numpy_norm_B)

#A8
def mean(data):
  total = 0
  for value in data:
    total += value
  return total/len(data)

def variance(data):
  mean_value = mean(data)
  total = 0
  for value in data:
    total += (value - mean_value)**2
  return total/len(data)

def std(data):
  variance_value = variance(data)
  return variance_value**0.5

def dataset_statistics(dataframe):
    numeric_df = dataframe.select_dtypes(include=['number'])

    for column in numeric_df.columns:
        values = numeric_df[column].tolist()

        my_mean = mean(values)
        my_variance = variance(values)
        my_std = std(values)

        print("Feature :", column)
        print("Mean :", my_mean)
        print("Variance :", my_variance)
        print("Standard Deviation :", my_std)
        print("-" * 40)

dataset_statistics(label_df)

#A9

numeric_df = label_df.select_dtypes(include=['number'])

for column in numeric_df.columns:
    values = numeric_df[column].values

    my_mean = mean(values)
    my_std = std(values)

    numpy_mean = np.mean(values)
    numpy_std = np.std(values)

    print("Feature :", column)
    print("My Mean :", my_mean)
    print("NumPy Mean :", numpy_mean)

    print("My Standard Deviation :", my_std)
    print("NumPy Standard Deviation :", numpy_std)

    print("-" * 50)

#A10

feature = label_df["Income"].dropna()

hist, bins = np.histogram(feature, bins=10)

print("Histogram Counts:")
print(hist)

print("\nBin Edges:")
print(bins)

mean_value = np.mean(feature)
variance_value = np.var(feature)

print("\nMean :", mean_value)
print("Variance :", variance_value)

plt.hist(feature, bins=10, edgecolor='black')
plt.title("Histogram of Income")
plt.xlabel("Income")
plt.ylabel("Frequency")
plt.show()

from sklearn.cluster import KMeans

numeric_df = label_df.select_dtypes(include=['number'])

numeric_df = numeric_df.dropna()

kmeans = KMeans(n_clusters=3, random_state=42, n_init='auto')

kmeans.fit(numeric_df)

labels = kmeans.labels_

centroids = kmeans.cluster_centers_

print("Cluster Labels:")
print(labels)

print("\nCluster Centroids:")
print(centroids)

print("\nNumber of Points in Each Cluster:")
for i in range(3):
    print("Cluster", i + 1, ":", (labels == i).sum())